#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Proj_4_Guardians.Resource", IsApplication=true)]

namespace Proj_4_Guardians
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CardBoard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drink_bottle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Electric = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Glas = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ImageBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Paper = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int QuestionMark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Recycle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int RoundButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int RoundImageButton = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int BtnInfo = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int BtnMap = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int BtnZoekCat = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int BtnZoekCat2 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int BtnZoekFin = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int BtnZoekMain = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int Cat2But1 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int Horizontalseparator = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int ImbAnders = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int ImbDrank = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int ImbElektro = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int ImbPapier = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int ImbRecycle = 2131099672;
			
			// aapt resource value: 0x7f060000
			public const int Menu = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int Searchseparator = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int Separator = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int TxtBenaming = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int TxtInfo = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int TxtNaam = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int TxvAnders = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int TxvDrank = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int TxvElektro = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int TxvPapier = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int Verticalseparator = 2131099649;
			
			// aapt resource value: 0x7f06001a
			public const int btnMenu = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int button2 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int button3 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int imageButton1 = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int lv = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int sv = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int txtMenu = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int txtv3 = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Achievement_Reward = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Category = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Category2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExtraInfo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Finalinfo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Tester = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Zoeken = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int recycler = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
